### ISSUE TITLE
VERSION is null

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq-pricenode-deprecated#5]
Version in bisq.pricenode.Main is not set.

Jan-24 19:17:01.007 [main] INFO  b.p.Main: bisq-pricenode version: null 

VERSION = Main.class.getPackage().getImplementationVersion();

**Comment by cbeams** [comment]
Closing as fixed in commit 1718ee7.

The reason you were seeing this `null` value, I presume, is because you ran the app directly from source in IDEA. This is fine to do—and you'll now see the version set to `0.0.0` when you do—but for the version to actually be populated, you need to build and run the app as instructed in the README, e.g.:

```
$ ./gradlew installDist # this builds the jar and sets up the run scripts used below
[...]
BUILD SUCCESSFUL

$ BITCOIN_AVG_PUBKEY=[pubkey] BITCOIN_AVG_PRIVKEY=[privkey] ./build/install/bisq-pricenode/bin/bisq-pricenode
[...]
12:51:54.311 [main] INFO  bisq.pricenode.Main - bisq-pricenode version: 0.7.0
[...]
```

Note how the version is set and reported as expected above.
