### ISSUE TITLE
Gradle setup question

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq-pricenode-deprecated#6]
The current provider is running in a loop so it gets restarted automatically if it would fail. Not sure if that is really needed. I will test mine without that. But wanted to check how such a script would be used with the gradle version  where no shaded jar is created. The install script in gradle is rather complex to adjust it directly...

```
#!/bin/bash
while true
do
echo `date`  "(Re)-starting provider"
java -jar exchange/provider/target/provider.jar [priv key] [pub key] 2 5 3 > /dev/null 2>errors_provider.log
echo `date` "provider terminated unexpectedly!!"
sleep 3
done
```

**Comment by ManfredKarrer** [comment]
Ah and there is another script which starts the loop script in nohup mode:
```
nohup sh run.sh &
```

So I use this now in the run.sh which gets started by the above script.
```
BITCOIN_AVG_PUBKEY=[pub key] BITCOIN_AVG_PRIVKEY=[priv key] ./pricenode/build/install/bisq-pricenode/bin/bisq-pricenode 2 5 3 > /dev/null 2>errors_provider.log
```

**Comment by cbeams** [comment]
@ManfredKarrer, what is the status of monitoring pricenodes? I'd prefer not to have them in a loop like this to automatically restart them if they fail. I'd rather just make sure they just don't fail in the first place.

If we have reliable monitoring on them, we should be able to track down the source of any such failures and root it out. If we just have a script that restarts them whenever they fail, there's no incentive to fix the underlying problem.

Maybe I'm missing something, please fill me in if so.

**Comment by ManfredKarrer** [comment]
Price nodes are monitored in mikes monitoring at http://188.166.2.139:8080/status
Yes I agree the loops should be not needed at price nodes. It was added for the seed nodes as they run out of memory after a while.

**Comment by cbeams** [comment]
Closing as answered. We'll try running without the loops for now. But a few other notes:

> wanted to check how such a script would be used with the gradle version where no shaded jar is created.

A shaded (i.e. fat executable) jar can be created. I just left that out of the build for now, until its clearly wanted / needed.

> The install script in gradle is rather complex to adjust it directly...

Those generated scripts definitely should not be edited. Their generation can be tweaked programmatically in the build script, but still, I'd leave them alone. If we end up needing another simple wrapper for our own purposes, that's the way I'd recommend going.

> Price nodes are monitored in mikes monitoring at http://188.166.2.139:8080/status

The problem here is that no one gets notified when something is wrong. My understanding is that we have to check the website, which almost certainly means we won't find out about our nodes being down until users complain about them. This (monitoring and alerts) is a different topic, though, so I'll leave it there for now.
